# Generated by Django 4.2.7 on 2024-03-12 12:33

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="subcategory",
            old_name="subcategory",
            new_name="category",
        ),
    ]
