# Generated by Django 4.2.7 on 2024-03-12 12:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0002_rename_subcategory_subcategory_category"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="subcategory",
            name="category",
        ),
        migrations.AddField(
            model_name="category",
            name="subcategory",
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to="main.subcategory"),
            preserve_default=False,
        ),
    ]
