# Generated by Django 4.2.7 on 2024-03-12 13:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0003_remove_subcategory_category_category_subcategory"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="category",
            name="subcategory",
        ),
        migrations.AddField(
            model_name="subcategory",
            name="subcategory",
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to="main.category"),
            preserve_default=False,
        ),
    ]
