# Generated by Django 4.2.7 on 2024-03-12 13:06

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0004_remove_category_subcategory_subcategory_subcategory"),
    ]

    operations = [
        migrations.RenameField(
            model_name="subcategory",
            old_name="subcategory",
            new_name="category",
        ),
    ]
